---
- name: copy  local to remote file
  become: true
  copy:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz


- name: Creates directory
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Extract 'artifact.tar.gz' into '/home/ubuntu/backend'
  become: true
  shell: |
    cd /home/ubuntu/backend
    tar -vxf artifact.tar.gz
    rm artifact.tar.gz


- name: Executing node
  become: true
  shell: |   
    cd /home/ubuntu/backend
    npm install
    npm run build   
    pm2 stop default
    pm2 start npm --name "backend" -- start