---
- name: copy  local to remote file
  become: true
  copy:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz


- name: Extract backend file
  become: true
  shell: |
    cd /home/ubuntu
    tar -vxf artifact.tar.gz
    rm artifact.tar.gz


- name: Executing node
  become: true
  shell: |   
    cd /home/ubuntu
    npm install
    npm run build   
    pm2 stop default
    pm2 start npm --name "backend" -- start